# thx to: https://sourcery.ai/blog/github-actions/

name: Process data

on: [] #[push, pull_request]

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies with pipenv
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install --deploy --dev

      - name: Compile data feed
        run: pipenv run python scripts/process_data.py

      - name: Commit generated ./json/index.json
        uses: EndBug/add-and-commit@v9
        with:
          message: "Commit updated static feed"
          add: "output/*"
          cwd: "."
          force: true
          default_author: github_actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
